#
# Dockerfile for tinyproxy
#

FROM alpine:3
COPY eq-tinyproxy-image/tinyproxy.conf /etc/tinyproxy/tinyproxy.conf
RUN apk update && apk add --no-cache tinyproxy=1.11.1-r3
VOLUME /etc/tinyproxy
EXPOSE 8888
